project:
  type: website
  output-dir: docs
  resources:
    - "*.pdf"

website:
  title: "Alexandros Karagiannis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/Alexander71747
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/alexandros-karagiannis-340739263/
        target: _blank
  search: true

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: false
    page-layout: full

editor: visual


